[package]
name = "file-loader"
version = "0.0.1"
edition = "2018"

[dependencies]
magic-crypt = "3.1.8"
base64 = "0.13.0"

[dependencies.file-loader-procedural]
git = "https://github.com/DmitrijVC/file-loader-procedural"

[dependencies.strenc]
git = "https://github.com/DmitrijVC/strenc"
